spring.application.name=gateway-resilience

server.port=8080

# Route Configuration
spring.cloud.gateway.routes[0].id=employee-service

spring.cloud.gateway.routes[0].uri=http://localhost:8081

spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**

# Circuit Breaker Filter
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=myCircuitBreaker

spring.cloud.gateway.routes[0].filters[1]=RewritePath=/employee/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[0].filters[2]=FallbackHeaders

spring.cloud.gateway.routes[0].filters[3]=FallbackUri=forward:/fallback

# Resilience4j
resilience4j.circuitbreaker.instances.myCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.myCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.myCircuitBreaker.failureRateThreshold=50