spring.application.name=gateway-loadbalancer

server.port=8080

spring.cloud.gateway.routes[0].id=employee-service

spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE

spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**